services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=magaludb
    ports:
      - "5432:5432"
  rabbitmq:
    container_name: 'rabbitmq-notification'
    image: 'rabbitmq:4.0-management'

    ports:
      - '5672:5672'
      - '15672:15672'